from utils.CONSTANTS import API_DOMAIN

taxonomies = {
    'Asset-Type': {
        'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/fund/process/asset/v2/',
        'component': 'sal-components-mip-asset-allocation',
        'jsonpath': '$.allocationMap',
        'category': '',
        'percent': 'netAllocation',
        'table': 0,
        'column': 2,
        'map':{
            "AssetAllocNonUSEquity":"Stocks", 
            "CANAssetAllocCanEquity" : "Stocks", 
            "CANAssetAllocUSEquity" : "Stocks",
            "CANAssetAllocInternationalEquity": "Stocks",
            "AssetAllocUSEquity":"Stocks",
            "AssetAllocCash":"Cash",
            "CANAssetAllocCash": "Stocks",
            "AssetAllocBond":"Bonds", 
            "CANAssetAllocFixedIncome": "Bonds",
            "UK bond":"Bonds",
            "AssetAllocNotClassified":"Other",
            "AssetAllocOther":"Other",
            "CANAssetAllocOther": "Other"
        }
    },
    'Region': {'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/fund/portfolio/regionalSector/',
               'component': 'sal-components-mip-region-exposure',
               'jsonpath': '$.fundPortfolio',
               'category': '',
               'percent': '',
               'table': 2,
               'column': 0,
               'map': {"northAmerica": "North America",
                           "europeDeveloped": "Developed Europe",
                           "asiaDeveloped": "Developed Asia",
                           "asiaEmerging": "Emerging Asia",
                           "australasia": "Australasia",
                           "europeDeveloped": "Developed Europe",
                           "europeEmerging": "Emerging Europe / Russia",
                           "japan": "Japan",
                           "latinAmerica": "Central & Latin America",
                           "unitedKingdom": "United Kingdom",
                           "africaMiddleEast": "Middle East / Africa",
                       },
               'map2': {"United States": "North America",
                        "Canada": "North America",
                        "Western Europe - Euro": "Developed Europe",
                        "Western Europe - Non Euro": "Developed Europe",
                        "Emerging 4 Tigers": "Developed Asia",
                        "Emerging Asia - Ex 4 Tigers": "Emerging Asia",
                        "Australasia": "Australasia",
                        "Emerging Europe": "Emerging Europe / Russia",
                                  "Japan": "Japan",
                                  "Central & Latin America": "Central & Latin America",
                                  "United Kingdom": "United Kingdom",
                                  "Middle East / Africa": "Middle East / Africa",
                                  "Not Classified": "Not Classified",
                        }
               },
    'Country': {'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/fund/portfolio/regionalSectorIncludeCountries/',
                'component': 'sal-components-mip-country-exposure',
                'jsonpath': '$.fundPortfolio.countries[*]',
                'category': 'name',
                'percent': 'percent',
                'table': 2,
                'column': 0,
                'map': {
                    "unitedStates": "United States",
                    "Western Europe - Euro": "Western Europe - Euro",
                    "Western Europe - Non Euro": "Western Europe - Non Euro",
                    "Emerging 4 Tigers": "Hong Kong, Singapore, South Korea and Taiwan",
                    "Emerging Asia - Ex 4 Tigers": "Emerging Asia",
                    "Australasia": "Australasia",
                    "Emerging Europe": "Emerging Europe / Russia",
                    "hongKong": 'Hong Kong',
                    'newZealand': 'New Zealand',
                    'czechRepublic': 'Czech Republic',
                    "Central & Latin America": "Central & Latin America",
                    "unitedKingdom": "United Kingdom",
                    "Middle East / Africa": "Middle East / Africa",
                    'southAfrica': 'South Africa',
                    'southKorea': 'South Korea',
                    "Not Classified": "Not Classified",
                }
                },
    'Sector': {'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/fund/portfolio/v2/sector/',
               'component': 'sal-components-mip-sector-exposure',
               'jsonpath': '$.EQUITY.fundPortfolio',
               'category': '',
               'percent': '',
               'table': 1,
               'column': 0,
               'map': {"basicMaterials": "Basic Materials",
                           "communicationServices": "Communication Services",
                           "consumerCyclical": "Consumer Cyclical",
                           "consumerDefensive": "Consumer Defensive",
                           "energy": "Energy",
                           "financialServices": "Financial Services",
                           "healthcare": "Healthcare",
                           "industrials": "Industrials",
                           "realEstate": "Real Estate",
                           "technology": "Technology",
                           "utilities": "Utilities",
                       }
               },
    'Market-cap': {'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/etf/process/marketCap/',
                   'component': 'sal-components-mip-market-cap',
                   'jsonpath': '$.fund',
                   'category': 'name',
                   'percent': '',
                   'table': 2,
                   'column': 0,
                   },

    'Stock-style': {'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/etf/process/weighting/',
                    'component': 'sal-components-mip-style-weight',
                    'jsonpath': '$',
                    'category': '',
                    'percent': '',
                    'table': 9,
                    'column': 2,
                    'map': {
                        "largeBlend": "Large Blend",
                                 "largeGrowth": "Large Growth",
                                 "largeValue": "Large Value",
                                 "middleBlend": "Mid-Cap Blend",
                                 "middleGrowth": "Mid-Cap Growth",
                                 "middleValue": "Mid-Cap Value",
                                 "smallBlend": "Small Blend",
                                 "smallGrowth": "Small Growth",
                                 "smallValue": "Small Value",
                    }
                    },
    'Currency': {'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/fund/portfolio/holding/v2/',
                 'component': 'sal-components-mip-holdings',
                 'jsonpath': '$.equityHoldingPage.holdingList[*]',
                 'category': 'currencyName',
                 'sector': '',
                 'percent': '',
                 'table': 6,
                 'column': 4,
                 },
    'ESG Risk': {'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/fund/portfolio/holding/v2/',
                 'component': 'sal-components-mip-holdings',
                 'jsonpath': '$.equityHoldingPage.holdingList[*]',
                 'category': 'susEsgRiskCategory',
                 'sector': '',
                 'percent': '',
                 'table': 6,
                 'column': 4,
                 },
    'Holding': {'url': f'https://www.{API_DOMAIN}-api.morningstar.com/sal/sal-service/fund/portfolio/holding/v2/',
                'component': 'sal-components-mip-holdings',
                'jsonpath': '$.equityHoldingPage.holdingList[*]',
                'category': 'securityName',
                'sector': 'sector',
                'percent': 'weighting',
                'table': 6,
                'column': 4,
                },
}